name: test web-scraping-puppeteer

on:
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: node:20
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies for Puppeteer
        run: |
          apt-get update
          apt-get install -y wget ca-certificates curl gnupg
          apt-get install -y fonts-liberation libappindicator3-1 libnss3 libxss1 libasound2
          apt-get install -y libatk-bridge2.0-0 libatk1.0-0 libcups2 libgdk-pixbuf2.0-0
          apt-get install -y libnspr4 libx11-xcb1 libxtst6 libnss3 libgdk-pixbuf2.0-0
          apt-get install -y libappindicator3-1 libxrandr2 libgbm1 libu2f-udev

      - run: npm ci

      - name: Run tests
        run: npm test

      - name: Run Vitest tests
        env:
          SCRAPER_URL: ${{ secrets.SCRAPER_URL }}
          SEARCH_TERM: ${{ secrets.SEARCH_TERM }}
        run: npx vitest run